Rails.application.routes.draw do
  resources :students, :path => "estudiante"
  resources :attendants, :path => "acudiente"
  resources :tracing_types, :path => "seguimiento"
  resources :working_days, :path => "jornada"
  resources :grades, :path => "grado"
  resources :genders, :path => "genero"
  resources :observer_details, :path => "detalle"
  resources :observer_heads, :path => "encabezado"
  resources :profiles, :path => "perfil"
  resources :users, :path => "usuario"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #Crear un alias, con la asignacion le indico el controlador y accion.
  # get "users" => "users#index"
  # post "users/login"
  # get "users/register"
  # post "users/save_register"
  # get "profiles/register"
  # post "profiles/save_register"
  # get "students/register"
  # post "students/save_register"
  # get "users/consult"
  # get "profiles/consult"
  # get "students/consult"
  # get "users/modify"
  # get "profiles/modify"
  # get "students/modify"
  # get "users/remove"
  # get "profiles/remove"
  # get "students/remove"
# Methods and Routes Observar Head
  #get "observer_heads" => "observer_heads#index"
# Methods and Routes Observar Details
  #get "observer_dateils" => "observer_dateils#index"
end
